### PR TITLE
Sky lighting improved

### PR DESCRIPTION
**Pull request by PonderSlime**
I took a look at the issue you had earlier, and i think i can help with some of the scene lighting. What I did is add a directional light and changed the environment to a procedural sky

### CODE REVIEW

**Comment by abc-is-here** [comment]
I am really glad you took time for this!
Thanks!!

**Comment by PonderSlime** [comment]
No problem!

**Comment by PonderSlime** [comment]
@abc-is-here I have fixed the player movement for you

**Comment by PonderSlime** [comment]
@abc-is-here I have fixed the player movement for your game. The issue was that _unhandled input is not supported for some reason. I changed it to an _input() function instead

**Comment by PonderSlime** [comment]
I have fixed the pause menu. The issue is that you were calling get_tree().paused on an object that was getting paused

**Comment by abc-is-here** [comment]
Wow Thanks It works!

**Review by abc-is-here — COMMENTED** [review]
Nice Thanks!

**Pull request closed without merging**
